"""add chat table

Revision ID: b2e9623cbb55
Revises: 7c610dcad31d
Create Date: 2025-03-02 23:34:47.966715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e9623cbb55'
down_revision = '7c610dcad31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('car_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('license_plate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('license_plate',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('car_model',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
